# Generated by Django 5.0 on 2023-12-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCuenta',
            fields=[
                ('old_id', models.IntegerField()),
                ('new_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_balance', models.IntegerField()),
                ('new_balance', models.IntegerField()),
                ('old_iban', models.TextField()),
                ('new_iban', models.TextField()),
                ('old_type', models.IntegerField()),
                ('new_type', models.IntegerField()),
                ('user_action', models.TextField()),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'auditoria_cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('customer_surname', models.TextField()),
                ('customer_dni', models.BinaryField(db_column='customer_DNI')),
                ('dob', models.TextField(blank=True, null=True)),
                ('branch_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
                ('tipocuenta', models.IntegerField(blank=True, db_column='tipoCuenta', null=True)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField()),
                ('employee_surname', models.TextField()),
                ('employee_hire_date', models.TextField()),
                ('employee_dni', models.TextField(db_column='employee_DNI')),
                ('branch_id', models.IntegerField()),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcatarjeta', models.TextField(db_column='marcaTarjeta')),
            ],
            options={
                'db_table': 'MarcaTarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('tipo_operacion', models.TextField()),
                ('hora', models.TextField()),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(choices=[('BLACK', 'Black'), ('GOLD', 'Gold'), ('CLASSIC', 'Classic')], max_length=10)),
                ('loan_date', models.DateField()),
                ('loan_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'prestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_number', models.BinaryField()),
                ('branch_name', models.TextField()),
                ('branch_address_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero', models.TextField(blank=True, db_column='Numero', null=True, unique=True)),
                ('cvv', models.IntegerField(blank=True, db_column='CVV', null=True)),
                ('fechaotorgamiento', models.DateField(blank=True, db_column='FechaOtorgamiento', null=True)),
                ('fechaexpiracion', models.DateField(blank=True, db_column='FechaExpiracion', null=True)),
                ('tipotarjeta', models.TextField(blank=True, db_column='TipoTarjeta', null=True)),
            ],
            options={
                'db_table': 'Tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
            ],
            options={
                'db_table': 'TipoCliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipocuenta', models.TextField(db_column='tipoCuenta')),
            ],
            options={
                'db_table': 'TipoCuenta',
                'managed': False,
            },
        ),
    ]
